import { Inter } from "next/font/google";
import "../styles/tailwind.css";
import { BasicLayout } from "@/components/Layouts/BasicLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html className="h-full bg-white" lang="ja">
      <body className={`${inter.className} h-full`}>
        <BasicLayout>{children}</BasicLayout>
      </body>
    </html>
  );
};

export default RootLayout;
